apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-workflow-service
  namespace: devops-ssd-assignment
  labels:
    app: invoice-workflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-workflow-service
  template:
    metadata:
      labels:
        app: invoice-workflow-service
    spec:
      containers:
        - name: app
          image: invoice-workflow-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RULES_PATH
              value: /runtime/rules.json
            - name: RELEASE_ID_FILE
              value: /runtime/release_id.txt
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.monitoring.svc.cluster.local:4318
            - name: OTEL_SERVICE_NAME
              value: invoice-workflow-service
