apiVersion: v1
kind: Service
metadata:
  name: invoice-workflow-service
  namespace: devops-ssd-assignment
  labels:
    app: invoice-workflow-service
spec:
  selector:
    app: invoice-workflow-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
