apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-workflow-deployment
  labels:
    app: expense-workflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-workflow
  template:
    metadata:
      labels:
        app: expense-workflow
    spec:
      containers:
      - name: expense-workflow-container
        image: expense-workflow-service:05f1de7ce8ed
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
