apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-workflow
  namespace: devops-ssd-assignment
  labels:
    app: expense-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-workflow
  template:
    metadata:
      labels:
        app: expense-workflow
    spec:
      containers:
        - name: app
          image: expense-workflow-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RULES_PATH
              value: /runtime/rules.json
            - name: RELEASE_ID_FILE
              value: /runtime/release_id.txt
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.monitoring.svc.cluster.local:4318
            - name: OTEL_SERVICE_NAME
              value: expense-workflow
