apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-workflow
  namespace: devops-ssd-assignment
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expense-workflow
                port:
                  number: 80
