apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: purchase-request-workflow-service
  namespace: argocd
spec:
  destination:
    namespace: devops-ssd-assignment
    server: https://kubernetes.default.svc
  project: default
  source:
    path: devops/k8s/purchase-request-workflow-service
    repoURL: https://github.com/Legiang98/devops-sdd-assignment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
