apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-ssd-assignment
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: devops/k8s/argocd
    repoURL: git@github.com:Legiang98/devops-sdd-assignment.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
